### ISSUE TITLE
The otel::tracing log level is not set to the same or lower level than TRACING_LEVEL, which makes span.set_parent() invalid.

### ISSUE THREAD

**Issue by Lvzhenqian** [davidB/tracing-opentelemetry-instrumentation-sdk#148]
Cargo.toml
```toml
axum = "0.7"
tracing = "0.1"
tracing-opentelemetry = "0.24.0"
opentelemetry = "0.23.0"
opentelemetry_sdk = { version = "0.23.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.16", features = ["trace", "tonic"] }
opentelemetry-semantic-conventions = "0.15"
axum-tracing-opentelemetry = "0.19"
tracing-opentelemetry-instrumentation-sdk = { version = "0.19", features = [
    "tracing_level_info",
] }
init-tracing-opentelemetry = "0.19"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "local-time",
    "ansi",
    "json",
] }
tracing-appender = "0.2"
```

The span generated before setting will not bring in the traceparent id of the http request:
![1](https://github.com/user-attachments/assets/00870cf2-66a6-4541-a440-aad7eac0083c)
After configuring the tagger log level, it can be normally associated with the incoming trace:
![2](https://github.com/user-attachments/assets/642db7a1-2037-4ecd-9738-2d42d9f65d8e)
