### ISSUE TITLE
init-tracing-opentelemetry: Regression on flushing all traces at program termination

### ISSUE THREAD

**Issue by nshalman** [davidB/tracing-opentelemetry-instrumentation-sdk#184]
I believe this to be a consequence of https://github.com/open-telemetry/opentelemetry-rust/issues/1961

Using these versions:
```toml
[dependencies]
init-tracing-opentelemetry = { version = "0.19", features = [
  "otlp",
  "tls",
  "tracing_subscriber_ext",
] }
opentelemetry = "0.23"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
```

This code works (I can get a trace):
```rust
#[tracing::instrument]
async fn hello() -> () {
    tracing::info!("Hello World!");
}

#[tokio::main]
async fn main() {
    match std::env::var("OTEL_SERVICE_NAME") {
        Ok(_) => (),
        Err(_) => std::env::set_var("OTEL_SERVICE_NAME", "hello"),
    };
    init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().expect("Tracing setup");
    hello().await;
    opentelemetry::global::shutdown_tracer_provider();
}
```

But when I change to these versions, the trace doesn't get emitted:
```toml
[dependencies]
init-tracing-opentelemetry = { version = "0.24", features = [
  "otlp",
  "tls",
  "tracing_subscriber_ext",
] }
opentelemetry = "0.27"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
```

With this grossest of workarounds I can get the trace to show up again:
```diff
@@ -12,4 +12,5 @@ async fn main() {
     init_tracing_opentelemetry::tracing_subscriber_ext::init_subscribers().expect("Tracing setup");
     hello().await;
     opentelemetry::global::shutdown_tracer_provider();
+    std::thread::sleep(std::time::Duration::from_millis(8000));
 }

```
