### ISSUE TITLE
bug: init-tracing-opentelemetry >0.26 fails to compile with tls feature

### ISSUE THREAD

**Issue by dpasirst** [davidB/tracing-opentelemetry-instrumentation-sdk#234]
I have not had a chance to investigate but wanted to share: upgraded version from 0.26 to 0.28 and it now has this error:

```
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `tonic`
 --> .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/init-tracing-opentelemetry-0.28.0/src/otlp.rs:4:43
  |
4 | use {opentelemetry_otlp::WithTonicConfig, tonic::transport::ClientTlsConfig};
  |                                           ^^^^^ use of unresolved module or unlinked crate `tonic`
  |
```

I'm not sure what has changed, but I'm reverting for now.

**Comment by davidB** [comment]
The tonic dependency becomes optional, but `tls` means grpc+tls.
I'll try to publish a fix tomorrow.

**Comment by davidB** [comment]
I'm not able to reproduce. I also used `cargo hack` to test against several features configuration.
FYI `tonic` is a transitive dependency of `opentelemetry-otlp` (it's why the crates doesn't need to explicitly add it for feature)

```sh
❯ cargo tree --features tls -i tonic
tonic v0.12.3
├── opentelemetry-otlp v0.29.0
│   └── init-tracing-opentelemetry v0.28.0 (/mnt/nvme0n1p1/david/src/github.com/davidB/tracing-opentelemetry-instrumentation-sdk/init-tracing-opentelemetry)
└── opentelemetry-proto v0.29.0
    └── opentelemetry-otlp v0.29.0 (*)
```

When you upgrade `init-tracing-opentelemetry`, did you upgrade `opentelemetry` accordingly (if you declare it explicitly)?

Reminder: Having multiple versions of opentelemetry generates troubles.
see https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/tree/main/init-tracing-opentelemetry#troubleshot-why-no-trace

**Comment by dpasirst** [comment]
some findings:
It seems that `tls` by itself works; however, when combined with other features such as `otlp` or `tracing_subscriber_ext`, the issue is triggered. This was not a problem with 0.26.

How to repro:
for reference: `rustc 1.87.0 (17067e9ac 2025-05-09)` but when I first reported this, I was on an older version of rustc. 

```shell
$ cargo init repro-tls
```

`Cargo.toml`
```toml
[package]
name = "init-tracing-opentelemetry-repro"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4" }
axum-tracing-opentelemetry = "0.28.0"
tokio = { version = "1.45.0", features = ["full"] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "std"] }
init-tracing-opentelemetry = { version = "0.28.1", features = [
    "otlp",
    "tracing_subscriber_ext",
    "tls",
] }
tracing-opentelemetry-instrumentation-sdk = { version = "0.28.1", features = [
    "http",
] }
opentelemetry = { version = "0.29.1", features = ["metrics"] }
```

`main.rs`
```rust
use axum::{response::Html, routing::get, Router};

#[tokio::main]
async fn main() {
    // build our application with a route
    let app = Router::new().route("/", get(handler));

    // run it
    let listener = tokio::net::TcpListener::bind("127.0.0.1:3000")
        .await
        .unwrap();
    println!("listening on {}", listener.local_addr().unwrap());
    axum::serve(listener, app).await.unwrap();
}

async fn handler() -> Html<&'static str> {
    Html("<h1>Hello, World!</h1>")
}
```
